### ISSUE TITLE
1 suggestion

### ISSUE THREAD

**Issue by T8star1984** [kealiu/ComfyUI-ZeroShot-MTrans#1]
can you provide a sample workflow,please

**Comment by T8star1984** [comment]
I have done ,thanks for you node,it's very helpful

**Comment by inferno46n2** [comment]
Is this not just… IPAdapter with inpainting? 😅

**Comment by kealiu** [comment]
I aggred with you.  hahaha.  😅

as explain in #2 , the paper enchance IPA material transfer with depth & illumination information, which give out a better output.

**Comment by kealiu** [comment]
update the READM with a sample workflow node detail

**Comment by kealiu** [comment]
As commit 9625be3, add sample workflow.
